#!/bin/bash
# python -m spacy download en
# python -m spacy download en_core_web_lg
# python -m ipykernel install --user --name=ChenXiang
# Import the workspace into JupyterLab
#jupyter lab workspaces import binder/workspace.json
